set(PICO_APPS_URL_BASE "https://github.com/raspberrypi/pico-apps/tree/HEAD")
macro(apps_auto_set_url TARGET)
    file(RELATIVE_PATH URL_REL_PATH "${PICO_APPS_PATH}" "${CMAKE_CURRENT_LIST_DIR}")
    pico_set_program_url(${TARGET} "${PICO_APPS_URL_BASE}/${URL_REL_PATH}")
endmacro()