#define WOKWI
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "pico/float.h"     // Required for using single-precision variables.
#include "pico/double.h"    // Required for using double-precision variables.



float singlePrecisionPI(float precision){                           //using float to calculate the number in single precision method
	float p = 2.0;                                                  //initialize the first number in the wallis product
    float pi = 2.0;                                                 //initialize pi and update it in the following loop 
    for(int i = 2; i <= precision * 2; i += 2) {                    //loop 100000 times and get a pi that generated by wallis product
        pi = pi * ((p = i) / (i - 1)) * (p / (i + 1));              //2 2 4 4 6 6 8 8 
    }                                                               //1 3 3 5 5 7 7 9
    return pi;
}

double doublePrecisionPI(double precision) {                         //using double to calculate the number in double precision method
    double p = 2.0;                                                  //initialize the first number in the wallis product
    double pi = 2.0;                                                 //initialize pi and update it in the following loop
    for(int i = 2; i <= precision * 2; i += 2) {                     //loop 100000 times and get a pi that generated by wallis product
        pi = pi * ((p = i) / (i - 1)) * (p / (i + 1));               //2 2 4 4 6 6 8 8
    }                                                                //1 3 3 5 5 7 7 9
    return pi;
}

int main(){

#ifndef WOKWI
    // Initialise the IO as we will be using the UART
    // Only required for hardware and not needed for Wokwi
    stdio_init_all();
#endif

	float pi = singlePrecisionPI(100000);
    puts("single precision pi is : ");
	printf("%.60f\n",pi);                                                           //get the remaining 60 digit of numbers
    float singlePrecisionError = pi - 3.14159265359;                                //calculate the single precision error
    if(singlePrecisionError < 0) singlePrecisionError = -singlePrecisionError;      //get the positive value
    puts("single precision error is : ");
    printf("%.60f\n",singlePrecisionError);

    double pi1 = doublePrecisionPI(100000);
    puts("double precision pi is : ");
	printf("%.60f\n",pi1);                                                          //get the remaining 60 digit of numbers
    double doublePrecisionError = pi1 - 3.14159265359;                              //calculate the single precision error
    if(doublePrecisionError < 0) doublePrecisionError = -doublePrecisionError;      //get the positive value
    puts("double precision error is : ");
    printf("%.60f\n",doublePrecisionError);

	return(0);
}