#include <stdio.h>
#include <stdlib.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "ws2812.pio.h"
#include "hardware/watchdog.h"

#define IS_RGBW true  // Will use RGBW format
#define NUM_PIXELS 1  // There is 1 WS2812 device in the chain
#define WS2812_PIN 28 // The GPIO pin that the WS2812 connected to

#define WELCOME "************************************************************************************\n*									           *\n*		LEARN MORSE CODE - An interactive game on the RP2040               *\n*									           *\n************************************************************************************\n*										   *\n*	Welcome to our game! This code was written by Group 27 in CSU23021	   *\n*										   *\n*			Some instructions to get you started:			   *\n*										   *\n*1. Choose your level by entering the morse code for the level number (don't worry *\n*   yet, these are provided for now.                                               *\n*2. Enter a (dot) by pressing the GP21 button on the MAKER-PI-PICO board for a     *\n*   short duration (255ms or less), and enter a (dash) by pressing the GP21        *\n*   button on the MAKER-PI-PICO board for a longer duration (longer than 255ms)    *\n*3. You will begin with 3 lives. Each time a correct answer is input, you will gain*\n*   a life (with 3 lives maximum), and each time your answer is incorrect, a life  *\n*   will be deducted. The RGB LED will indicate how many lives you have got left:  *\n*   				PURPLE: 3 lives                                    *\n*   			        ORANGE: 2 lives                                    *\n*                               RED: 1 life                                        *\n*                               OFF: 0 lives, GAME OVER                            *\n*										   *\n************************************************************************************\n" // welcome msg

// Declare the main assembly code entry point.
void main_asm();

/* -------------------------------------------- GIPO Initialzation -------------------------------------------- */

// Initialise a GPIO pin – see SDK for detail on gpio_init()
void asm_gpio_init(uint pin)
{
    gpio_init(pin);
}

// Set direction of a GPIO pin – see SDK for detail on gpio_set_dir()
void asm_gpio_set_dir(uint pin, bool out)
{
    gpio_set_dir(pin, out);
}

// Get the value of a GPIO pin – see SDK for detail on gpio_get()
bool asm_gpio_get(uint pin)
{
    return gpio_get(pin);
}

// Set the value of a GPIO pin – see SDK for detail on gpio_put()
void asm_gpio_put(uint pin, bool value)
{
    gpio_put(pin, value);
}

// Enable rising and falling-edge interrupt – see SDK for detail on gpio_set_irq_enabled()
void asm_gpio_set_irq(uint pin)
{
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_FALL, true);
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_RISE, true);
}

/* -------------------------------------------- Watchdog initialization -------------------------------------------- */

void watchdog_init()
{
    if (watchdog_caused_reboot())
    { // check if reboot was due to watchdog timeout
        printf("\nNo input was detected for timeout period. Rebooted by watchdog\n");
    }
    if (watchdog_enable_caused_reboot())
    { // check if enabling watchdog caused reboot
        printf("\nChip reboot due to watchdog enable\n");
    }
    watchdog_enable(0x7fffff, 1); // enable the watchdog timer to max time (approx 8.3 secs), pause on debug
    watchdog_update();
}

/* -------------------------------------------- RGB LED -------------------------------------------- */

// code for initialising RGB LED
/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 *
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb)
{
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 *
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b)
{
    return ((uint32_t)(r) << 8) |
           ((uint32_t)(g) << 16) |
           (uint32_t)(b);
}

// Set the correct LED colour depending on the number of lives remaining
void RGB_Lives_Display(int remaining_lives)
{
    if (remaining_lives == 0)
    {
        put_pixel(urgb_u32(0x00, 0x00, 0x00)); // Set the RGB LED off
        printf("Game over!!!\n");
    }
    else if (remaining_lives == 1)
    {
        put_pixel(urgb_u32(0x7F, 0x00, 0x00)); // Set the RGB LED color to red
        printf("Warning! 1 life remaining.\n");
    }
    else if (remaining_lives == 2)
    {
        put_pixel(urgb_u32(0xFF, 0xA5, 0x00)); // Set the RGB LED color to orange
        printf("2 lives remaining.\n");
    }
    else if (remaining_lives == 3)
    {
        put_pixel(urgb_u32(0x4B, 0x00, 0x82)); // Set the RGB LED color to purple
        printf("Congratulations! 3 lives remaining.\n");
    }
    else
    {
        printf("Throw error detection.\n");
    }
}

/* -------------------------------------------- Button pressed Timing -------------------------------------------- */

// Get a timestamp in milliseconds
int get_time_in_ms()
{
    absolute_time_t time = get_absolute_time();
    return to_ms_since_boot(time);
}

// Find the time difference in milliseconds
int get_time_difference(int end_time, int start_time)
{
    return (end_time - start_time);
}

/* -------------------------------------------- Global Variables -------------------------------------------- */

int Remaining_Lives = 3; // Current lives the player has
int Gained_Lives = 0;    // Records the number of lives the player has gained
int Correct_Counter = 0; // records the number of correct answers in a row
int levelIndex = 0;
char *userInput;     // This array stores the user inputs
int userInputLength; // The length of the array userInput
int lastInput;

char inputSequence[20];
int i = 0; // i = length of input sequence
int tmpIndex = 0;
int inputComplete = 0;
int Remain_Counter = 5;
int Wrong_Counter = 0;

int select_level_input = 0;

/* -------------------------------------------- Morse Code Table -------------------------------------------- */

#define table_SIZE 36

typedef struct morsecode
{
    char letter;
    char *code;
} morsecode;
morsecode table[table_SIZE];

void morse_init()
{

    table[0].letter = 'A';
    table[1].letter = 'B';
    table[2].letter = 'C';
    table[3].letter = 'D';
    table[4].letter = 'E';
    table[5].letter = 'F';
    table[6].letter = 'G';
    table[7].letter = 'H';
    table[8].letter = 'I';
    table[9].letter = 'J';
    table[10].letter = 'K';
    table[11].letter = 'L';
    table[12].letter = 'M';
    table[13].letter = 'N';
    table[14].letter = 'O';
    table[15].letter = 'P';
    table[16].letter = 'Q';
    table[17].letter = 'R';
    table[18].letter = 'S';
    table[19].letter = 'T';
    table[20].letter = 'U';
    table[21].letter = 'V';
    table[22].letter = 'W';
    table[23].letter = 'X';
    table[24].letter = 'Y';
    table[25].letter = 'Z';
    table[26].letter = '0';
    table[27].letter = '1';
    table[28].letter = '2';
    table[29].letter = '3';
    table[30].letter = '4';
    table[31].letter = '5';
    table[32].letter = '6';
    table[33].letter = '7';
    table[34].letter = '8';
    table[35].letter = '9';

    table[0].code = ".-";
    table[1].code = "-...";
    table[2].code = "-.-.";
    table[3].code = "-..";
    table[4].code = ".";
    table[5].code = "..-.";
    table[6].code = "--.";
    table[7].code = "....";
    table[8].code = "..";
    table[9].code = ".---";
    table[10].code = "-.-";
    table[11].code = ".-..";
    table[12].code = "--";
    table[13].code = "-.";
    table[14].code = "---";
    table[15].code = ".--.";
    table[16].code = "--.-";
    table[17].code = ".-.";
    table[18].code = "...";
    table[19].code = "-";
    table[20].code = "..-";
    table[21].code = "...-";
    table[22].code = ".--";
    table[23].code = "-..-";
    table[24].code = "-.--";
    table[25].code = "--..";
    table[26].code = "-----";
    table[27].code = ".----";
    table[28].code = "..---";
    table[29].code = "...--";
    table[30].code = "....-";
    table[31].code = ".....";
    table[32].code = "-....";
    table[33].code = "--...";
    table[34].code = "---..";
    table[35].code = "----.";
}

static const char *alp[] = {
    ".-",    // A
    "-...",  // B
    "-.-.",  // C
    "-..",   // D
    ".",     // E
    "..-.",  // F
    "--.",   // G
    "....",  // H
    "..",    // I
    ".---",  // J
    "-.-",   // K
    ".-..",  // L
    "--",    // M
    "-.",    // N
    "---",   // O
    ".--.",  // P
    "--.-",  // Q
    ".-.",   // R
    "...",   // S
    "-",     // T
    "..-",   // U
    "...-",  // V
    ".--",   // W
    "-..-",  // X
    "-.--",  // Y
    "--..",  // Z
    "-----", // 0
    ".----", // 1
    "..---", // 2
    "...--", // 3
    "....-", // 4
    ".....", // 5
    "-....", // 6
    "--...", // 7
    "---..", // 8
    "----.", // 9
};

static const char *que[] = {
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
};

/* -------------------------------------------- Starting Game -------------------------------------------- */

// Function to start the game and turn the LED to green after level is chosen
void gameStart()
{
    put_pixel(urgb_u32(0x00, 0x7F, 0x00)); // Set the RGB LED color to green
    Correct_Counter = 0;
    Remaining_Lives = 3;
    Remain_Counter = 5;
    Wrong_Counter = 0;
    Gained_Lives = 0;
}

/* -------------------------------------------- Level Selection -------------------------------------------- */

void level_select_true(){
    select_level_input = 1;
}

void level_select_false(){
    select_level_input = 0;
}

int select_level(){

    if (strcmp(inputSequence, alp[27])==0){    // return 1 for level 1
        printf("Level 1 selected");
        return 1;
    }
    else if(strcmp(inputSequence, alp[28])==0){    // return 2 for level 2
        printf("Level 2 selected");
        return 2;
    }
    else if(strcmp(inputSequence, alp[29])==0){    // return 3 for level 3
        printf("Level 3 selected");
        return 3;
    }
    else if(strcmp(inputSequence, alp[30])==0){    // return 4 for level 4
        printf("Level 4 selected");
        return 4;
    }
    else{
        return 5;   // return 5 for invalid result
    }

}

// Random number generator, for getting a random letter/number from the morese code table
int r(int low, int high)
{
    if (low > high)
        return high;
    return low + (rand() % (high - low + 1));
}
int level_1_question()
{
    levelIndex = 1;
    int tmp = r(0, 35);
    tmpIndex = tmp;
    printf("\n");
    printf("||================================================||\n");
    printf("||     Reproduce this character in morse code     ||\n");
    printf("                          %s                        \n", alp[tmp]);
    printf("                          %s                        \n", que[tmp]);
    printf("||================================================||\n");
    return tmp;
}

int level_2_question()
{
    levelIndex = 2;
    int tmp = r(0, 35);
    tmpIndex = tmp;
    printf("\n");
    printf("||================================================||\n");
    printf("||           What is this in morse code?          ||\n");
    printf("                         %c                         \n", table[tmp].letter);
    printf("||================================================||\n");
    return tmp;
}

int level3QuestionIdx = 0;

int level_3_question() {
	levelIndex = 3;
	int toReturn = 0;
	if (level3QuestionIdx == 0) {
		toReturn=36;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"PICO\" in morse code\n");
		printf(".--...-.-.---\n");
        printf("================================================\n");
		level3QuestionIdx = 1;
		return toReturn;
	}
	if (level3QuestionIdx == 1) {
		toReturn =37;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"CODE\" in morse code\n");
		printf("-.-.----...\n");
        printf("================================================\n");
		level3QuestionIdx = 2;
		return toReturn;
	}
	if (level3QuestionIdx == 2) {
		toReturn =38;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"MICRO\" in morse code\n");
		printf("--..-.-..-.---\n");
        printf("================================================\n");
		level3QuestionIdx = 3;
		return toReturn;
	}
	if (level3QuestionIdx == 3) {
		toReturn =39;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"INTEL\" in morse code\n");
		printf("..-.-..-..\n");
        printf("================================================\n");
		level3QuestionIdx = 4;
		return toReturn;
	}
	if (level3QuestionIdx == 4) {
		toReturn =40;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"GROUP\" in morse code\n");
		printf("--..-.---..-.--.\n");
        printf("================================================\n");
		level3QuestionIdx = 0;
		return toReturn;
	}	
	return toReturn;
}

int level4QuestionIdx = 0;

int level_4_question() {
	levelIndex = 4;
	int toReturn = 0;
	if (level4QuestionIdx == 0) {
		toReturn=36;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"PICO\" in morse code\n");
        printf("================================================\n");
		level4QuestionIdx = 1;
		return toReturn;
	}
	if (level4QuestionIdx == 1) {
		toReturn =37;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"CODE\" in morse code\n");
        printf("================================================\n");
		level4QuestionIdx = 2;
		return toReturn;
	}
	if (level4QuestionIdx == 2) {
		toReturn =38;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"MICRO\" in morse code\n");
        printf("================================================\n");
		level4QuestionIdx = 3;
		return toReturn;
	}
	if (level4QuestionIdx == 3) {
		toReturn =39;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"INTEL\" in morse code\n");
        printf("================================================\n");
		level4QuestionIdx = 4;
		return toReturn;
	}
	if (level4QuestionIdx == 4) {
		toReturn =40;
		tmpIndex = toReturn;
		printf("\n");
        printf("================================================\n");
		printf("Reproduce the word \"GROUP\" in morse code\n");
        printf("================================================\n");
		level4QuestionIdx = 0;
		return toReturn;
	}	
	return toReturn;
}

int get_level()
{
    return levelIndex;
}

void set_level(int level)
{
    levelIndex = level;
}

int check_level_complete()
{
    if (Correct_Counter == 5)
    {
        return 1;
    }
    if (Remaining_Lives == 0)
    {
        printf("\n");
        printf("||=================================||\n");
        printf("||                                 ||\n");
        printf("||      No Lives remaining         ||\n");
        printf("||  Sorry, you've lost the game    ||\n");
        printf("||                                 ||\n");
        printf("||=================================||\n");
        printf("\n");
        printf("||========================================||\n");
        printf("||             Statistics Table           ||\n");
        printf("||             Correct times: %d          ||\n", Correct_Counter);
        printf("||             Wrong times: %d            ||\n", Wrong_Counter);
        printf("||             Gained Lives: %d           ||\n", Gained_Lives);
        printf("||             Remaining Lives: %d        ||\n", Remaining_Lives);
        printf("||========================================||\n");
        printf("\n");
        return 2;
    }
    return 0;
}

/* -------------------------------------------- Reading Inputs -------------------------------------------- */

// Initalize the global input array
void initalizeInputArray()
{
    int maxsize = 20;
    for (int j = 0; j < maxsize; j++)
    {
        inputSequence[j] = NULL;
    }
    inputComplete = 0;
    i = 0;
}

// Function to check input dot & dash
void detectInput(int input)
{
    if (input == 1)
    {                           // 1 = "."
        inputSequence[i] = '.'; // add '.' to the array
        i++;
        printf(".");
    }
    else if (input == 2)
    {                           // 2 = "-"
        inputSequence[i] = '-'; // add '-' to the array
        i++;
        printf("-");
    }
    else if (input == 3)
    {                           // 3 = " "
        inputSequence[i] = ' '; // add ' ' to the array
        i++;
        printf(" ");
    }
    else if (input == 4 && select_level_input == 1){
        inputSequence[i-1] = NULL;  // 4 = "enter"

        inputComplete = 1;  // value = 1 if answer is correct, otherwise remain 0
        select_level();
    }
    else if (input == 4 && select_level_input == 0){
        inputSequence[i-1] = NULL;  // 4 = "enter"

        inputComplete = 1;  // value = 1 if answer is correct, otherwise remain 0
        display_user_input();
        RGB_Lives_Display(Remaining_Lives);
    }
}

/* -------------------------------------------- Checking Answer -------------------------------------------- */

// Function to compare input of user to expected sequence
int checkAnswer()
{
    if (strcmp(inputSequence, alp[tmpIndex])==0)
    {
        // if (inputSequence == table[tmpIndex].code){
        return 1; // return 1 if equal
    }
    else
        return 0; // return 0 if not
}

// Function to check equivalence of morse code to A-Z/0-9
int checkMorseCode()
{
    for (int i = 0; i < table_SIZE; i++)
    {
        if (inputSequence == table[i].code)
        {
            return i;
        }
    }
    return -1; // return -1 if not equivalence
}

/* -------------------------------------------- Printing Game Messages -------------------------------------------- */

void Display_Welcome_Messages()
{
    printf(WELCOME);
}

/*
void update_remaining_lives(bool answer)
{
    if (answer)
    {
        printf("||=================================||\n");
        printf("||   Correct! One life was added.  ||\n");
        printf("||=================================||\n");
        put_pixel(urgb_u32(0x00, 0x7F, 0x00)); // Set the RGB LED color to green
        Gained_Lives ++;
        Correct_Counter ++;
        if (Remaining_Lives == 3)
        {
        printf("||========================================================||\n");
        printf("||     You already reach the maximum amount of lives      ||\n");
        printf("||========================================================||\n");
        put_pixel(urgb_u32(0x00, 0x7F, 0x00)); // Set the RGB LED color to green
        }
        else
        {
            Remaining_Lives += 1;
            RGB_Lives_Display(Remaining_Lives);
        }
    }
    else
    {
        printf("||=================================||\n");
        printf("||     Wrong! One life was taken.  ||\n");
        printf("||=================================||\n");
        Correct_Counter--;
        Remaining_Lives -= 1;
        put_pixel(urgb_u32(0x7F, 0x00, 0x00)); // Set the RGB LED color to red
        RGB_Lives_Display(Remaining_Lives);
    }
}
*/

bool game_continue()
{
    if (Remaining_Lives <= 0)
    {
        return 0;
    }
    return 1;
}

void level_success()
{
    printf("\n");
    printf("========================================\n");
    printf("Complete current level %d!\n", levelIndex);
    printf("========================================\n");
    printf("\n");
    printf("||========================================||\n");
    printf("||             Statistics Table           ||\n");
    printf("||             Correct times: 5           ||\n");
    printf("||             Wrong times: %d            ||\n", Wrong_Counter);
    printf("||             Gained Lives: %d           ||\n", Gained_Lives);
    printf("||             Remaining Lives: %d        ||\n", Remaining_Lives);
    printf("||========================================||\n");
    printf("\n");
}

void game_won_display()
{
    printf("||=======================================||\n");
    printf("||                                       ||\n");
    printf("||   Congurtulations! You won the game!  ||\n");
    printf("||                                       ||\n");
    printf("||=======================================||\n");
}

void game_over_display()
{
    printf("||=================================||\n");
    printf("||                                 ||\n");
    printf("||   Sorry, you lost the game!     ||\n");
    printf("||                                 ||\n");
    printf("||=================================||\n");
}

void display_level_choosing()
{
    printf("\n");
    printf("You can choose the corresponding level according to the difficulty\n");
    printf("For level 1, type in corresponding morse code for number 1(.----)\n");
    printf("For level 2, type in corresponding morse code for number 2(..---)\n");
    printf("For level 3, type in corresponding morse code for number 3(...--)\n");
    printf("For level 4, type in corresponding morse code for number 4(....-)\n");
}

void level_selection_invalid(){
    printf("||=======================================||\n");
    printf("||                                       ||\n");
    printf("||    Invalid Input, please try again    ||\n");
    printf("||                                       ||\n");
    printf("||=======================================||\n");
}

void incorrectInputlvl1()
{
    printf("\n");
    printf("\n");
    printf("||================================================||\n");
    printf("||                You entered:                    ||\n");
    printf("                     %s                             \n", inputSequence);
    printf("                   %s  =  %s                        \n", alp[tmpIndex], que[tmpIndex]);
    printf("||       this did not match any sequence          ||\n");
    printf("||================================================||\n");
    Remaining_Lives--;
    printf("\n");
    printf("||=================================||\n");
    printf("||     Wrong! One life was token.  ||\n");
    printf("||=================================||\n");
    Wrong_Counter++;
}

void incorrectInputlvl3()
{
    printf("\n");
    printf("\n");
    printf("||================================================||\n");
    printf("||                You entered:                    ||\n");
    printf("                     %s                             \n", inputSequence);
    printf("||       this did not match any sequence          ||\n");
    printf("||================================================||\n");
    Remaining_Lives--;
    printf("\n");
    printf("||=================================||\n");
    printf("||     Wrong! One life was token.  ||\n");
    printf("||=================================||\n");
    Wrong_Counter++;
}

void correctInputlvl1()
{
    printf("\n");
    printf("\n");
    Correct_Counter++;
    Remain_Counter--;
    printf("||================================================||\n");
    printf("||                You entered:                    ||\n");
    printf("                   %s  =  %s                        \n", alp[tmpIndex], que[tmpIndex]);
    printf("   You have correct %d time(s),  %d time(s) left    \n", Correct_Counter, Remain_Counter);
    printf("||================================================||\n");
    if (Remaining_Lives < 3)
    {
        Remaining_Lives++;
        printf("\n");
        printf("||=================================||\n");
        printf("||   Correct! One life was added.  ||\n");
        printf("||=================================||\n");
        Gained_Lives++;
    }
}

void correctInputlvl3()
{
    printf("\n");
    printf("\n");
    Correct_Counter++;
    Remain_Counter--;
    printf("||================================================||\n");
    printf("||                You entered:                    ||\n");
    printf("                   %s                         \n", inputSequence);
    printf("   You have correct %d time(s),  %d time(s) left    \n", Correct_Counter, Remain_Counter);
    printf("||================================================||\n");

    if (Remaining_Lives < 3)
    {
        Remaining_Lives++;
        printf("\n");
        printf("||=================================||\n");
        printf("||   Correct! One life was added.  ||\n");
        printf("||=================================||\n");
        Gained_Lives++;
    }
}

void display_user_input()
{
    if (tmpIndex >= 0 && tmpIndex <= 35)
    {
        int temp = checkAnswer();
        if (inputComplete == 1)
        {
            if (temp == 0)
            {
                incorrectInputlvl1();
            }
            else
            {
                correctInputlvl1();
            }
        }
    }
    if (tmpIndex == 36)
    {
        if (strcmp(inputSequence, ".--...-.-.---")==0)
        { // if input morse = "pico"
            correctInputlvl3();
        }
        else
        {
            incorrectInputlvl3();
        }
    }
    else if (tmpIndex == 37)
    {
        if (strcmp(inputSequence, "-.-.----...")==0)
        { // if input morse = "code"
            correctInputlvl3();
        }
        else
        {
            incorrectInputlvl3();
        }
    }
    else if (tmpIndex == 38)
    {
        if (strcmp(inputSequence, "--..-.-..-.---")==0)
        { // if input morse = "micro"
            correctInputlvl3();
        }
        else
        {
            incorrectInputlvl3();
        }
    }
    else if (tmpIndex == 39)
    {
        if (strcmp(inputSequence, "..-.-..-..")==0)
        { // if input morse = "intel"
            correctInputlvl3();
        }
        else
        {
            incorrectInputlvl3();
        }
    }
    else if (tmpIndex == 40)
    {
        if (strcmp(inputSequence == "--..-.---..-.--.")==0)
        { // if input morse = "group"
            correctInputlvl3();
        }
        else
        {
            incorrectInputlvl3();
        }
    }
    else
    {
        printf("error");
    }
}


/* -------------------------------------------- Main function -------------------------------------------- */

int main()
{
    // Initialise all STDIO
    stdio_init_all();
    morse_init();
    watchdog_init();

    // Initialise the PIO interface with the WS2812 code (FOR RBG LED)
    // initialisePIO();
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);
    put_pixel(urgb_u32(0x00, 0x00, 0x7F)); // Set the RGB LED color to blue

    printf(WELCOME);

    // Jump into the main assembly code subroutine.
    watchdog_update();
    main_asm();

    // Returning zero indicates everything went okay.
    return 0;
}
