#include <stdio.h>

#include "pico/stdlib.h"
#include "hardware/adc.h"
#include "lab09.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define lab09_PIN 28        // The GPIO pin that the WS2812 is connected to

// Must declare the main assembly entry point before use.
void main_asm();

/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

// Initialise the PIO interface with the WS2812 code
void initialisePIO () {
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &lab09_program);
    lab09_program_init(pio, 0, offset, lab09_PIN, 800000, IS_RGBW);
}

// Initialise the RP2040 ADC and enable the temperature sensor
void asm_adc_init () {
    adc_init();                             // Initialise the ADC
    adc_set_temp_sensor_enabled(true);      // Enable the temperature sensor
}

// Select an ADC input
void asm_adc_select_input (uint input) {
    adc_select_input(input);
}

// Read the ADC value from the temperature sensor
uint16_t readTemperature () {
    uint16_t result = adc_read();
    return result;
}

/**
 * @brief Function to take in raw ADC values and convert it to a
 *        floating point representation, sets the RGB LED to  an
 *        appropriate colour based on the temperature reading
 *        -- red temp>30 C
 *        -- orange 10 C< temp <30 C
 *        -- green temp<10 C
 * 
 * @param rawADC     The raw ADC value that is read by the temperature sensor
 */
void floatTemperatureReading(uint16_t rawADC) {
    const float conversion_factor = 3.3f / (1 << 12);
    float temp = 27 - ((rawADC * conversion_factor) - 0.706)/0.001721;
    printf("Temperature reading: %f C\n", temp);

    if(temp <= 10){
        // If temp is less than 10 C, set colour to green
        put_pixel(urgb_u32(0x00, 0x7F, 0x00));
    }
    else if(temp >= 30){
        // If temp is greater than 30 C, set colour to red
        put_pixel(urgb_u32(0x3F, 0x00, 0x00));
    }
    else{
        // If temp is between 10 C and 30 C, set colour to orange
        put_pixel(urgb_u32(0xCC, 0x70, 0x00));
    }
}

/**
 * @brief LAB #09 - Reading temperatures and displaying colours
 *        Main entry point for the code - calls the main assembly
 *        function where the body of the code is implemented.
 * 
 * @return int      Returns exit-status zero on completion.
 */
int main() {
    stdio_init_all();              // Initialise all basic IO
    initialisePIO();               // Initialise the PIO interface with the WS2812 code
    printf("Lab09...\n");          // Basic print to console

    // Initialise the PIO interface with the WS2812 code
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &lab09_program);
    lab09_program_init(pio, 0, offset, lab09_PIN, 800000, IS_RGBW);

    // Jump into the main assembly code subroutine.
    main_asm();

    // Returning zero indicates everything went okay.
    return 0;
}